### ISSUE TITLE
Upload to splunkbase

### ISSUE THREAD

**Issue by olafhartong** [secops4thewin/link_analysis_app#1]
Hey man, I love your visualisations and use them a LOT.
Are you planning to upload this one to SplunkBase as well? 
I want to use it in one of my public apps, having it up there would ease the installation for most users.

**Comment by secops4thewin** [comment]
This will be uploaded to https://splunkbase.splunk.com/app/4676/ by .conf.  Version 1.6.0 is the final release pending the tonne of bugs that will inevitably be found :-D
